In [ ]:
import pandas as pd 
import numpy as np

df = pd.read_csv('data.csv')

,date,country,continent,confirmed_cases,deaths,recovered,tests_done,vaccinations
0,2020-12-13 09:00:00,USA,North America,491582.0,12213.0,45832.0,888848.0,412233.0
1,2020-07-02 12:00:00,Brazil,South America,449840.0,1943.0,72622.0,NaN,126948.0
2,2020-02-09 11:00:00,Germany,Europe,427485.0,6905.0,390670.0,136830.0,672999.0
3,2020-01-22 04:00:00,Russia,Europe,339252.0,16053.0,300459.0,173875.0,858869.0
4,2021-01-07 01:00:00,UK,Europe,228273.0,440.0,42711.0,233865.0,NaN

In [26]:
df['confirmed_cases'].fillna(df['confirmed_cases'].mean(), inplace=True)
df['deaths'].fillna(df['deaths'].mean(), inplace=True)
df['recovered'].fillna(df['recovered'].mean(), inplace=True)
df['tests_done'].fillna(df['tests_done'].mean(), inplace=True)
df['vaccinations'].fillna(df['vaccinations'].mean(), inplace=True)
df.drop_duplicates(inplace=True)
df['date'] = pd.to_datetime(df['date'])


df.info()

C:\Users\jhash\AppData\Local\Temp\ipykernel_7072\1252241507.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['confirmed_cases'].fillna(df['confirmed_cases'].mean(), inplace=True)
C:\Users\jhash\AppData\Local\Temp\ipykernel_7072\1252241507.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['deaths'].fillna(df['deaths'].mean(), inplace=True)
C:\Users\jhash\AppData\Local\Temp\ipykernel_7072\1252241507.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['recovered'].fillna(df['recovered'].mean(), inplace=True)
C:\Users\jhash\AppData\Local\Temp\ipykernel_7072\1252241507.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['tests_done'].fillna(df['tests_done'].mean(), inplace=True)
C:\Users\jhash\AppData\Local\Temp\ipykernel_7072\1252241507.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['vaccinations'].fillna(df['vaccinations'].mean(), inplace=True)

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 10199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             10000 non-null  datetime64[ns]
 1   country          10000 non-null  object
 2   continent        10000 non-null  object
 3   confirmed_cases  10000 non-null  float64
 4   deaths           10000 non-null  float64
 5   recovered        10000 non-null  float64
 6   tests_done       10000 non-null  float64
 7   vaccinations     10000 non-null  float64
dtypes: datetime64[ns](1), float64(5), object(2)
memory usage: 703.1+ KB

In [29]:
df.to_csv('cleaned_data.csv', index=False)